name: Build
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    strategy:
      matrix:
        # This comes from what node-serialport currently builds for
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        architecture:
          - x64
        target:
          - 9.4.4
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          architecture: ${{ matrix.architecture }}
      - run: npm install
      - name: Prebuild Serialport Bindings
        run: npx prebuild --verbose --force --strip --target ${{ matrix.target }} --runtime electron --path node_modules/@serialport/bindings/ --upload ${{ secrets.UPLOAD_TOKEN }}
