name: Build
on:
  push:
    tags: ['v[1-9]+.[0-9]+.[0-9]+']
jobs:
  build:
    strategy:
      matrix:
        config:
          # This comes from what node-serialport currently builds for
          - { os: macos-latest, arch: x64 }
          - { os: ubuntu-latest, arch: x64 }
          - { os: windows-latest, arch: x64 }
    runs-on: ${{ matrix.config.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Prebuild Serialport Bindings
        run: npx prebuild --verbose --force --strip --target ${{ matrix.target }} --runtime electron --path node_modules/@serialport/bindings/ --upload ${{ secrets.UPLOAD_TOKEN }}
